let a = {
  statusCode: 200,
  message: "成功",
  typeName: null,
  personName: null,
  data: [
    {
      personId: null,
      personCode: "A07430",
      personName: "李想",
      mobilePhone: "13905538630",
      email: "Lixiang10@lenovo.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "1900-01-01",
      personStatus: "离职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "A07572",
      personName: "王津",
      mobilePhone: "18522057882",
      email: "18522057882@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "1900-01-01",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "A07573",
      personName: "张龙",
      mobilePhone: "18661059115",
      email: "1761986128@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "1900-01-01",
      personStatus: "离职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "A09490",
      personName: "李轶希",
      mobilePhone: "18802278325",
      email: "634335989@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "1900-01-01",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "A09491",
      personName: "刘金玉",
      mobilePhone: "13821754953",
      email: "865153743@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "1900-01-01",
      personStatus: "离职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "C10183",
      personName: "赵丹",
      mobilePhone: "13069125321",
      email: "36749754@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2000-05-31",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C11553",
      personName: "杨斌",
      mobilePhone: "13808073151",
      email: "yangbin@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2007-04-08",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C14718",
      personName: "冯子续",
      mobilePhone: "13512953205",
      email: "fengzixu00@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-01-15",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C15109",
      personName: "郭晨",
      mobilePhone: "18686629183",
      email: "344027111@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2003-01-15",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C15990",
      personName: "李思东",
      mobilePhone: "13845050456",
      email: "lisd@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2000-08-21",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C16023",
      personName: "孙莉",
      mobilePhone: "18640035311",
      email: "sunli@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2001-02-28",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "C16307",
      personName: "苏嘉红",
      mobilePhone: "18192226517",
      email: "sujh@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-01-15",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C16308",
      personName: "宋德江",
      mobilePhone: "18509236587",
      email: "songdj@enos.com.cn",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2015-05-11",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C16897",
      personName: "周丽芳",
      mobilePhone: "18622335224",
      email: "Slibery@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2003-10-29",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "C16990",
      personName: "袁兴林",
      mobilePhone: "13881019733",
      email: "lenovo_yxl@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2003-01-10",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C17930",
      personName: "陈道亮",
      mobilePhone: "13512418488",
      email: "chendaoliangse@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-01-20",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C17987",
      personName: "王强",
      mobilePhone: "13019342323",
      email: "wangqiang@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-01-15",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C18322",
      personName: "张阳",
      mobilePhone: "13386839565",
      email: "zhangyanga@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-01-15",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C18919",
      personName: "李靖靖",
      mobilePhone: "15002974676",
      email: "lijin-1221@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2013-07-30",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C19272",
      personName: "王晓鑫",
      mobilePhone: "15046657858",
      email: "wangxx@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-01-15",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "C19676",
      personName: "马伟君",
      mobilePhone: "18640402177",
      email: "mawj@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-03-09",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "C19694",
      personName: "马文新",
      mobilePhone: "13920919864",
      email: "275519128@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-03-11",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C19833",
      personName: "刘琳琳",
      mobilePhone: "13936591686",
      email: "liull@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-04-01",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C20126",
      personName: "王嘉",
      mobilePhone: "13772149798",
      email: "wangjia@enos.com.cn",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-04-20",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C20502",
      personName: "张朝岗",
      mobilePhone: "13980708135",
      email: "329496797@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-05-30",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C20798",
      personName: "金龙",
      mobilePhone: "13578710386",
      email: "jltly@126.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-06-23",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C21375",
      personName: "王学亮",
      mobilePhone: "13504339419",
      email: "522363350@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-08-12",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C21640",
      personName: "陈俊君",
      mobilePhone: "13571803633",
      email: "25123844@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2005-09-08",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C22678",
      personName: "李松振",
      mobilePhone: "18702225889",
      email: "lishong-zhen@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2006-02-16",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C23191",
      personName: "李嘉臣",
      mobilePhone: "13662137831",
      email: "407235852@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2006-03-16",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C24455",
      personName: "金岩",
      mobilePhone: "17743014660",
      email: "jinyan1982@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2012-04-17",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C24779",
      personName: "陈斌",
      mobilePhone: "15829606841",
      email: "chenbin@enos.com.cn",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2019-11-05",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C25290",
      personName: "潘志敏",
      mobilePhone: "13034300822",
      email: "79003933@QQ.COM",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2006-08-21",
      personStatus: "离职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "C25310",
      personName: "陈德强",
      mobilePhone: "13920406620",
      email: "195822836@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2006-08-22",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C25824",
      personName: "陈婕",
      mobilePhone: "13820013265",
      email: "jessicabritish@yahoo.com.cn",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2006-07-30",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "C26331",
      personName: "姜旭",
      mobilePhone: "13630559471",
      email: "jiang_4429@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2006-12-20",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C26518",
      personName: "陈富雷",
      mobilePhone: "13946149876",
      email: "chenfld@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2007-01-15",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C27678",
      personName: "雷聪玲",
      mobilePhone: "18792452187",
      email: "leicl@enos.com.cn",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2008-12-03",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "C35183",
      personName: "衣方旭",
      mobilePhone: "13039317145",
      email: "491228515@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2007-06-27",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C35261",
      personName: "林志刚",
      mobilePhone: "18180837916",
      email: "596540319@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2007-06-28",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C35328",
      personName: "李双凤",
      mobilePhone: "13572015475",
      email: "lisf881107@126.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2007-07-06",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "C35605",
      personName: "王帅",
      mobilePhone: "18640593911",
      email: "wangshuai@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2007-07-18",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C37408",
      personName: "彭博",
      mobilePhone: "13945671017",
      email: "pengbo@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2007-10-23",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C39025",
      personName: "马艳龙",
      mobilePhone: "15947865971",
      email: "157940531@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2008-01-01",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C39563",
      personName: "田勇",
      mobilePhone: "18704661064",
      email: "tianyonga@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2008-01-28",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C39670",
      personName: "白银",
      mobilePhone: "15829294521",
      email: "baiyin369@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2008-01-29",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C40786",
      personName: "吴艳丽",
      mobilePhone: "15591052612",
      email: "wuyl@enos.com.cn",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2008-04-02",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "C40808",
      personName: "白金",
      mobilePhone: "13820932023",
      email: "76247102@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2008-04-07",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C40825",
      personName: "黄宇翔",
      mobilePhone: "18010695956",
      email: "huangyx@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2008-03-26",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C43065",
      personName: "吴飞",
      mobilePhone: "13804907892",
      email: "wufei@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2008-08-12",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C50548",
      personName: "李金华",
      mobilePhone: "18503057231",
      email: "lijhm@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2019-03-01",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "C51146",
      personName: "袁伟超",
      mobilePhone: "18920048833",
      email: "hopefirst@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2014-12-10",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C51652",
      personName: "鲜芝刚",
      mobilePhone: "13308238141",
      email: "380549858@QQ.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2009-12-26",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C51925",
      personName: "任晓梅",
      mobilePhone: "18113183158",
      email: "448232226@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2010-01-26",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "C53910",
      personName: "胡津利",
      mobilePhone: "13821501040",
      email: "hujinli0@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2010-05-26",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C55511",
      personName: "夏增榜",
      mobilePhone: "18706809769",
      email: "xiazb@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2010-09-01",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C56117",
      personName: "魏柱",
      mobilePhone: "13572545576",
      email: "weizhu0513@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2010-09-15",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "C57588",
      personName: "张明珠",
      mobilePhone: "13804536045",
      email: "zhangmz1@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2021-09-26",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "E00465",
      personName: "冷仁忠",
      mobilePhone: "13945151811",
      email: "110200@iservice.net.cn",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "1900-01-01",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "E01648",
      personName: "王爽",
      mobilePhone: "13940319900",
      email: "130800@iservice.net.cn",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "1900-01-01",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "E03557",
      personName: "付美竹",
      mobilePhone: "15881073081",
      email: "710300@iservice.net.cn",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "E08329",
      personName: "刘鑫",
      mobilePhone: "13079219775",
      email: "130800@iservice.net.cn",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "1900-01-01",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "E10560",
      personName: "周玉涛",
      mobilePhone: "17790941766",
      email: "130800@iservice.net.cn",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "1900-01-01",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "E20201",
      personName: "方亮",
      mobilePhone: "15840275559",
      email: "accsy@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2021-09-06",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "fanzb1",
      personName: "范智博",
      mobilePhone: "18911776250",
      email: "fanzb1@lenovo.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2017-08-01",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L10335",
      personName: "范玉祥",
      mobilePhone: "13468958546",
      email: "fanyx6382037@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2011-02-18",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L10337",
      personName: "郭锋涛",
      mobilePhone: "15229048054",
      email: "guoft0201@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2011-02-18",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L11035",
      personName: "米胜",
      mobilePhone: "13821804061",
      email: "75569318@QQ.COM",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2011-01-05",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L12484",
      personName: "林松",
      mobilePhone: "13821125131",
      email: "591197456@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2011-09-06",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L12574",
      personName: "杨金梅",
      mobilePhone: "13772051964",
      email: "410015@lenovoservice.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2020-07-08",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "L13287",
      personName: "李鹏",
      mobilePhone: "18010695937",
      email: "lipengg@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2011-11-11",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L13315",
      personName: "黎鹏",
      mobilePhone: "18180656151",
      email: "287882233@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2016-08-12",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L13345",
      personName: "蒋欢",
      mobilePhone: "15208320652",
      email: "287997479@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2011-11-15",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L13578",
      personName: "郝静",
      mobilePhone: "15590585188",
      email: "799353442@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2011-12-05",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "L13579",
      personName: "齐长伟",
      mobilePhone: "15122391232",
      email: "qic_wei@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2011-11-16",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L13581",
      personName: "马帅",
      mobilePhone: "13644410728",
      email: "188876311@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2011-12-08",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "L14115",
      personName: "薛学昌",
      mobilePhone: "18602934931",
      email: "xuexc410009@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2012-02-01",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L15289",
      personName: "王旭",
      mobilePhone: "18636864651",
      email: "wangxub@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2012-08-06",
      personStatus: "离职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L16015",
      personName: "张仕彬",
      mobilePhone: "18328333466",
      email: "zhangsbb@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2012-06-14",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L16764",
      personName: "叶倩",
      mobilePhone: "13551020893",
      email: "524956371@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2012-07-12",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "L17397",
      personName: "李思遥",
      mobilePhone: "18030580321",
      email: "1541582509@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2017-01-11",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L17722",
      personName: "段云峰",
      mobilePhone: "13666112151",
      email: "duanyunfeng.cool@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2012-10-19",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L18646",
      personName: "任静",
      mobilePhone: "18781937219",
      email: "1364830165@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2013-03-01",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L18647",
      personName: "袁旭",
      mobilePhone: "13183890715",
      email: "1036504581@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2017-07-26",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L18666",
      personName: "王世民",
      mobilePhone: "13940331175",
      email: "wangsmb@sunits.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2013-03-04",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L19456",
      personName: "李璐琳",
      mobilePhone: "18240293092",
      email: "1966244580@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2011-09-01",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "L19462",
      personName: "陈晓艳",
      mobilePhone: "15145147370",
      email: "15145147370@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2011-09-01",
      personStatus: "在职",
      sex: "女",
    },
    {
      personId: null,
      personCode: "L20287",
      personName: "曾杨",
      mobilePhone: "18583670388",
      email: "273531359@qq.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2013-09-02",
      personStatus: "在职",
      sex: "男",
    },
    {
      personId: null,
      personCode: "L25556",
      personName: "陈钟航",
      mobilePhone: "13669568640",
      email: "chenzhvm@163.com",
      idCardType: null,
      idCard: null,
      itCode: null,
      hireDate: "2020-03-27",
      personStatus: "在职",
      sex: "男",
    },
  ],
}
